// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArtArgData.proto

package com.zjucsc.capture_main.protobuf;

public final class ArtArgData {
  private ArtArgData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArtArgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zjucsc.ArtArg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */
    int getValuesCount();
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */
    boolean containsValues(
            String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @Deprecated
    java.util.Map<String, Float>
    getValues();
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */
    java.util.Map<String, Float>
    getValuesMap();
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */

    float getValuesOrDefault(
            String key,
            float defaultValue);
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */

    float getValuesOrThrow(
            String key);
  }
  /**
   * <pre>
   *定义结构数据
   * </pre>
   *
   * Protobuf type {@code com.zjucsc.ArtArg}
   */
  public  static final class ArtArg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zjucsc.ArtArg)
      ArtArgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArtArg.newBuilder() to construct.
    private ArtArg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArtArg() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ArtArg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArtArg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                values_ = com.google.protobuf.MapField.newMapField(
                    ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, Float>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(
                  values__.getKey(), values__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_zjucsc_ArtArg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_zjucsc_ArtArg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ArtArg.class, ArtArg.Builder.class);
    }

    public static final int VALUES_FIELD_NUMBER = 1;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, Float> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, Float>newDefaultInstance(
                  internal_static_com_zjucsc_ArtArg_ValuesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.FLOAT,
                  0F);
    }
    private com.google.protobuf.MapField<
        String, Float> values_;
    private com.google.protobuf.MapField<String, Float>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */

    public boolean containsValues(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, Float> getValues() {
      return getValuesMap();
    }
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */

    public java.util.Map<String, Float> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */

    public float getValuesOrDefault(
        String key,
        float defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Float> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>map&lt;string, float&gt; values = 1;</code>
     */

    public float getValuesOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Float> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<String, Float> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, Float>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, values__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ArtArg)) {
        return super.equals(obj);
      }
      ArtArg other = (ArtArg) obj;

      if (!internalGetValues().equals(
          other.internalGetValues())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ArtArg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArtArg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArtArg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArtArg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArtArg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ArtArg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ArtArg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ArtArg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ArtArg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ArtArg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ArtArg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ArtArg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ArtArg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义结构数据
     * </pre>
     *
     * Protobuf type {@code com.zjucsc.ArtArg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zjucsc.ArtArg)
        ArtArgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_zjucsc_ArtArg_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_zjucsc_ArtArg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ArtArg.class, ArtArg.Builder.class);
      }

      // Construct using ArtArg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        internalGetMutableValues().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_zjucsc_ArtArg_descriptor;
      }

      @Override
      public ArtArg getDefaultInstanceForType() {
        return ArtArg.getDefaultInstance();
      }

      @Override
      public ArtArg build() {
        ArtArg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ArtArg buildPartial() {
        ArtArg result = new ArtArg(this);
        int from_bitField0_ = bitField0_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ArtArg) {
          return mergeFrom((ArtArg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ArtArg other) {
        if (other == ArtArg.getDefaultInstance()) return this;
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ArtArg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ArtArg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          String, Float> values_;
      private com.google.protobuf.MapField<String, Float>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<String, Float>
      internalGetMutableValues() {
        onChanged();;
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>map&lt;string, float&gt; values = 1;</code>
       */

      public boolean containsValues(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, Float> getValues() {
        return getValuesMap();
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>map&lt;string, float&gt; values = 1;</code>
       */

      public java.util.Map<String, Float> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>map&lt;string, float&gt; values = 1;</code>
       */

      public float getValuesOrDefault(
          String key,
          float defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Float> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>map&lt;string, float&gt; values = 1;</code>
       */

      public float getValuesOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, Float> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>map&lt;string, float&gt; values = 1;</code>
       */

      public Builder removeValues(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, Float>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>map&lt;string, float&gt; values = 1;</code>
       */
      public Builder putValues(
          String key,
          float value) {
        if (key == null) { throw new NullPointerException(); }
        
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>map&lt;string, float&gt; values = 1;</code>
       */

      public Builder putAllValues(
          java.util.Map<String, Float> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zjucsc.ArtArg)
    }

    // @@protoc_insertion_point(class_scope:com.zjucsc.ArtArg)
    private static final ArtArg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ArtArg();
    }

    public static ArtArg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<ArtArg>
        PARSER = new com.google.protobuf.AbstractParser<ArtArg>() {
      @Override
      public ArtArg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArtArg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArtArg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ArtArg> getParserForType() {
      return PARSER;
    }

    @Override
    public ArtArg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zjucsc_ArtArg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zjucsc_ArtArg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zjucsc_ArtArg_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zjucsc_ArtArg_ValuesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020ArtArgData.proto\022\ncom.zjucsc\"g\n\006ArtArg" +
      "\022.\n\006values\030\001 \003(\0132\036.com.zjucsc.ArtArg.Val" +
      "uesEntry\032-\n\013ValuesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\002:\0028\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zjucsc_ArtArg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zjucsc_ArtArg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zjucsc_ArtArg_descriptor,
        new String[] { "Values", });
    internal_static_com_zjucsc_ArtArg_ValuesEntry_descriptor =
      internal_static_com_zjucsc_ArtArg_descriptor.getNestedTypes().get(0);
    internal_static_com_zjucsc_ArtArg_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zjucsc_ArtArg_ValuesEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
