// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttackBean.proto

package com.zjucsc.capture_main.protobuf;

public final class AttackBeanOuterClass {
  private AttackBeanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AttackBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zjucsc.AttackBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string attackType = 1;</code>
     */
    boolean hasAttackType();
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string attackType = 1;</code>
     */
    String getAttackType();
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string attackType = 1;</code>
     */
    com.google.protobuf.ByteString
        getAttackTypeBytes();

    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string attackInfo = 2;</code>
     */
    boolean hasAttackInfo();
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string attackInfo = 2;</code>
     */
    String getAttackInfo();
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string attackInfo = 2;</code>
     */
    com.google.protobuf.ByteString
        getAttackInfoBytes();
  }
  /**
   * <pre>
   *定义结构数据
   * </pre>
   *
   * Protobuf type {@code com.zjucsc.AttackBean}
   */
  public  static final class AttackBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zjucsc.AttackBean)
      AttackBeanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttackBean.newBuilder() to construct.
    private AttackBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttackBean() {
      attackType_ = "";
      attackInfo_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new AttackBean();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AttackBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              attackType_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              attackInfo_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_zjucsc_AttackBean_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_zjucsc_AttackBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AttackBean.class, AttackBean.Builder.class);
    }

    private int bitField0_;
    public static final int ATTACKTYPE_FIELD_NUMBER = 1;
    private volatile Object attackType_;
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string attackType = 1;</code>
     */
    public boolean hasAttackType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string attackType = 1;</code>
     */
    public String getAttackType() {
      Object ref = attackType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          attackType_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string attackType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAttackTypeBytes() {
      Object ref = attackType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        attackType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATTACKINFO_FIELD_NUMBER = 2;
    private volatile Object attackInfo_;
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string attackInfo = 2;</code>
     */
    public boolean hasAttackInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string attackInfo = 2;</code>
     */
    public String getAttackInfo() {
      Object ref = attackInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          attackInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string attackInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAttackInfoBytes() {
      Object ref = attackInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        attackInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAttackType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttackInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, attackType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, attackInfo_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, attackType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, attackInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AttackBean)) {
        return super.equals(obj);
      }
      AttackBean other = (AttackBean) obj;

      if (hasAttackType() != other.hasAttackType()) return false;
      if (hasAttackType()) {
        if (!getAttackType()
            .equals(other.getAttackType())) return false;
      }
      if (hasAttackInfo() != other.hasAttackInfo()) return false;
      if (hasAttackInfo()) {
        if (!getAttackInfo()
            .equals(other.getAttackInfo())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAttackType()) {
        hash = (37 * hash) + ATTACKTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getAttackType().hashCode();
      }
      if (hasAttackInfo()) {
        hash = (37 * hash) + ATTACKINFO_FIELD_NUMBER;
        hash = (53 * hash) + getAttackInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AttackBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AttackBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AttackBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AttackBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AttackBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AttackBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AttackBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AttackBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AttackBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AttackBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AttackBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AttackBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AttackBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义结构数据
     * </pre>
     *
     * Protobuf type {@code com.zjucsc.AttackBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zjucsc.AttackBean)
        AttackBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_zjucsc_AttackBean_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_zjucsc_AttackBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AttackBean.class, AttackBean.Builder.class);
      }

      // Construct using AttackBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        attackType_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        attackInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_zjucsc_AttackBean_descriptor;
      }

      @Override
      public AttackBean getDefaultInstanceForType() {
        return AttackBean.getDefaultInstance();
      }

      @Override
      public AttackBean build() {
        AttackBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AttackBean buildPartial() {
        AttackBean result = new AttackBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.attackType_ = attackType_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.attackInfo_ = attackInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AttackBean) {
          return mergeFrom((AttackBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AttackBean other) {
        if (other == AttackBean.getDefaultInstance()) return this;
        if (other.hasAttackType()) {
          bitField0_ |= 0x00000001;
          attackType_ = other.attackType_;
          onChanged();
        }
        if (other.hasAttackInfo()) {
          bitField0_ |= 0x00000002;
          attackInfo_ = other.attackInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasAttackType()) {
          return false;
        }
        if (!hasAttackInfo()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AttackBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AttackBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object attackType_ = "";
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string attackType = 1;</code>
       */
      public boolean hasAttackType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string attackType = 1;</code>
       */
      public String getAttackType() {
        Object ref = attackType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            attackType_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string attackType = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAttackTypeBytes() {
        Object ref = attackType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          attackType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string attackType = 1;</code>
       */
      public Builder setAttackType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        attackType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string attackType = 1;</code>
       */
      public Builder clearAttackType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attackType_ = getDefaultInstance().getAttackType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string attackType = 1;</code>
       */
      public Builder setAttackTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        attackType_ = value;
        onChanged();
        return this;
      }

      private Object attackInfo_ = "";
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string attackInfo = 2;</code>
       */
      public boolean hasAttackInfo() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string attackInfo = 2;</code>
       */
      public String getAttackInfo() {
        Object ref = attackInfo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            attackInfo_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string attackInfo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAttackInfoBytes() {
        Object ref = attackInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          attackInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string attackInfo = 2;</code>
       */
      public Builder setAttackInfo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attackInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string attackInfo = 2;</code>
       */
      public Builder clearAttackInfo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        attackInfo_ = getDefaultInstance().getAttackInfo();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string attackInfo = 2;</code>
       */
      public Builder setAttackInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        attackInfo_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zjucsc.AttackBean)
    }

    // @@protoc_insertion_point(class_scope:com.zjucsc.AttackBean)
    private static final AttackBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AttackBean();
    }

    public static AttackBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<AttackBean>
        PARSER = new com.google.protobuf.AbstractParser<AttackBean>() {
      @Override
      public AttackBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AttackBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AttackBean> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AttackBean> getParserForType() {
      return PARSER;
    }

    @Override
    public AttackBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zjucsc_AttackBean_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zjucsc_AttackBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020AttackBean.proto\022\ncom.zjucsc\"4\n\nAttack" +
      "Bean\022\022\n\nattackType\030\001 \002(\t\022\022\n\nattackInfo\030\002" +
      " \002(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zjucsc_AttackBean_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zjucsc_AttackBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zjucsc_AttackBean_descriptor,
        new String[] { "AttackType", "AttackInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
