// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FvDimension.proto

package com.zjucsc.capture_main.protobuf;

public final class FvDimension {
  private FvDimension() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FvDimensionLayerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.zjucsc.FvDimensionLayer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string frame_protocols = 1;</code>
     */
    boolean hasFrameProtocols();
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string frame_protocols = 1;</code>
     */
    String getFrameProtocols();
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string frame_protocols = 1;</code>
     */
    com.google.protobuf.ByteString
        getFrameProtocolsBytes();

    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string eth_dst = 2;</code>
     */
    boolean hasEthDst();
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string eth_dst = 2;</code>
     */
    String getEthDst();
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string eth_dst = 2;</code>
     */
    com.google.protobuf.ByteString
        getEthDstBytes();

    /**
     * <pre>
     *可选字段 第3个属性
     * </pre>
     *
     * <code>required string frame_cap_len = 3;</code>
     */
    boolean hasFrameCapLen();
    /**
     * <pre>
     *可选字段 第3个属性
     * </pre>
     *
     * <code>required string frame_cap_len = 3;</code>
     */
    String getFrameCapLen();
    /**
     * <pre>
     *可选字段 第3个属性
     * </pre>
     *
     * <code>required string frame_cap_len = 3;</code>
     */
    com.google.protobuf.ByteString
        getFrameCapLenBytes();

    /**
     * <code>required string eth_src = 4;</code>
     */
    boolean hasEthSrc();
    /**
     * <code>required string eth_src = 4;</code>
     */
    String getEthSrc();
    /**
     * <code>required string eth_src = 4;</code>
     */
    com.google.protobuf.ByteString
        getEthSrcBytes();

    /**
     * <code>required string ip_src = 5;</code>
     */
    boolean hasIpSrc();
    /**
     * <code>required string ip_src = 5;</code>
     */
    String getIpSrc();
    /**
     * <code>required string ip_src = 5;</code>
     */
    com.google.protobuf.ByteString
        getIpSrcBytes();

    /**
     * <code>required string ip_dst = 6;</code>
     */
    boolean hasIpDst();
    /**
     * <code>required string ip_dst = 6;</code>
     */
    String getIpDst();
    /**
     * <code>required string ip_dst = 6;</code>
     */
    com.google.protobuf.ByteString
        getIpDstBytes();

    /**
     * <code>required string src_port = 7;</code>
     */
    boolean hasSrcPort();
    /**
     * <code>required string src_port = 7;</code>
     */
    String getSrcPort();
    /**
     * <code>required string src_port = 7;</code>
     */
    com.google.protobuf.ByteString
        getSrcPortBytes();

    /**
     * <code>required string dst_port = 8;</code>
     */
    boolean hasDstPort();
    /**
     * <code>required string dst_port = 8;</code>
     */
    String getDstPort();
    /**
     * <code>required string dst_port = 8;</code>
     */
    com.google.protobuf.ByteString
        getDstPortBytes();

    /**
     * <code>required string timeStamp = 9;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>required string timeStamp = 9;</code>
     */
    String getTimeStamp();
    /**
     * <code>required string timeStamp = 9;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>required string funCode = 10;</code>
     */
    boolean hasFunCode();
    /**
     * <code>required string funCode = 10;</code>
     */
    String getFunCode();
    /**
     * <code>required string funCode = 10;</code>
     */
    com.google.protobuf.ByteString
        getFunCodeBytes();

    /**
     * <code>required string funCodeMeaning = 11;</code>
     */
    boolean hasFunCodeMeaning();
    /**
     * <code>required string funCodeMeaning = 11;</code>
     */
    String getFunCodeMeaning();
    /**
     * <code>required string funCodeMeaning = 11;</code>
     */
    com.google.protobuf.ByteString
        getFunCodeMeaningBytes();

    /**
     * <code>required int32 delay = 12;</code>
     */
    boolean hasDelay();
    /**
     * <code>required int32 delay = 12;</code>
     */
    int getDelay();

    /**
     * <code>required int32 collectorId = 13;</code>
     */
    boolean hasCollectorId();
    /**
     * <code>required int32 collectorId = 13;</code>
     */
    int getCollectorId();
  }
  /**
   * <pre>
   *定义结构数据
   * </pre>
   *
   * Protobuf type {@code com.zjucsc.FvDimensionLayer}
   */
  public  static final class FvDimensionLayer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.zjucsc.FvDimensionLayer)
      FvDimensionLayerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FvDimensionLayer.newBuilder() to construct.
    private FvDimensionLayer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FvDimensionLayer() {
      frameProtocols_ = "";
      ethDst_ = "";
      frameCapLen_ = "";
      ethSrc_ = "";
      ipSrc_ = "";
      ipDst_ = "";
      srcPort_ = "";
      dstPort_ = "";
      timeStamp_ = "";
      funCode_ = "";
      funCodeMeaning_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new FvDimensionLayer();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FvDimensionLayer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              frameProtocols_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              ethDst_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              frameCapLen_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              ethSrc_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              ipSrc_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              ipDst_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              srcPort_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000080;
              dstPort_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              timeStamp_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              funCode_ = bs;
              break;
            }
            case 90: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000400;
              funCodeMeaning_ = bs;
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              delay_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              collectorId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_com_zjucsc_FvDimensionLayer_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_com_zjucsc_FvDimensionLayer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FvDimensionLayer.class, FvDimensionLayer.Builder.class);
    }

    private int bitField0_;
    public static final int FRAME_PROTOCOLS_FIELD_NUMBER = 1;
    private volatile Object frameProtocols_;
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string frame_protocols = 1;</code>
     */
    public boolean hasFrameProtocols() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string frame_protocols = 1;</code>
     */
    public String getFrameProtocols() {
      Object ref = frameProtocols_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          frameProtocols_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *必选字段 第1个属性
     * </pre>
     *
     * <code>required string frame_protocols = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFrameProtocolsBytes() {
      Object ref = frameProtocols_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        frameProtocols_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ETH_DST_FIELD_NUMBER = 2;
    private volatile Object ethDst_;
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string eth_dst = 2;</code>
     */
    public boolean hasEthDst() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string eth_dst = 2;</code>
     */
    public String getEthDst() {
      Object ref = ethDst_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ethDst_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *必选字段 第2个属性
     * </pre>
     *
     * <code>required string eth_dst = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEthDstBytes() {
      Object ref = ethDst_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ethDst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FRAME_CAP_LEN_FIELD_NUMBER = 3;
    private volatile Object frameCapLen_;
    /**
     * <pre>
     *可选字段 第3个属性
     * </pre>
     *
     * <code>required string frame_cap_len = 3;</code>
     */
    public boolean hasFrameCapLen() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *可选字段 第3个属性
     * </pre>
     *
     * <code>required string frame_cap_len = 3;</code>
     */
    public String getFrameCapLen() {
      Object ref = frameCapLen_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          frameCapLen_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *可选字段 第3个属性
     * </pre>
     *
     * <code>required string frame_cap_len = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFrameCapLenBytes() {
      Object ref = frameCapLen_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        frameCapLen_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ETH_SRC_FIELD_NUMBER = 4;
    private volatile Object ethSrc_;
    /**
     * <code>required string eth_src = 4;</code>
     */
    public boolean hasEthSrc() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string eth_src = 4;</code>
     */
    public String getEthSrc() {
      Object ref = ethSrc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ethSrc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string eth_src = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEthSrcBytes() {
      Object ref = ethSrc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ethSrc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_SRC_FIELD_NUMBER = 5;
    private volatile Object ipSrc_;
    /**
     * <code>required string ip_src = 5;</code>
     */
    public boolean hasIpSrc() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string ip_src = 5;</code>
     */
    public String getIpSrc() {
      Object ref = ipSrc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipSrc_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip_src = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIpSrcBytes() {
      Object ref = ipSrc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ipSrc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_DST_FIELD_NUMBER = 6;
    private volatile Object ipDst_;
    /**
     * <code>required string ip_dst = 6;</code>
     */
    public boolean hasIpDst() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string ip_dst = 6;</code>
     */
    public String getIpDst() {
      Object ref = ipDst_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipDst_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip_dst = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIpDstBytes() {
      Object ref = ipDst_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ipDst_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRC_PORT_FIELD_NUMBER = 7;
    private volatile Object srcPort_;
    /**
     * <code>required string src_port = 7;</code>
     */
    public boolean hasSrcPort() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required string src_port = 7;</code>
     */
    public String getSrcPort() {
      Object ref = srcPort_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          srcPort_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string src_port = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSrcPortBytes() {
      Object ref = srcPort_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        srcPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DST_PORT_FIELD_NUMBER = 8;
    private volatile Object dstPort_;
    /**
     * <code>required string dst_port = 8;</code>
     */
    public boolean hasDstPort() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>required string dst_port = 8;</code>
     */
    public String getDstPort() {
      Object ref = dstPort_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dstPort_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dst_port = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDstPortBytes() {
      Object ref = dstPort_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dstPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private volatile Object timeStamp_;
    /**
     * <code>required string timeStamp = 9;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>required string timeStamp = 9;</code>
     */
    public String getTimeStamp() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timeStamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timeStamp = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCODE_FIELD_NUMBER = 10;
    private volatile Object funCode_;
    /**
     * <code>required string funCode = 10;</code>
     */
    public boolean hasFunCode() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>required string funCode = 10;</code>
     */
    public String getFunCode() {
      Object ref = funCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          funCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string funCode = 10;</code>
     */
    public com.google.protobuf.ByteString
        getFunCodeBytes() {
      Object ref = funCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        funCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCODEMEANING_FIELD_NUMBER = 11;
    private volatile Object funCodeMeaning_;
    /**
     * <code>required string funCodeMeaning = 11;</code>
     */
    public boolean hasFunCodeMeaning() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>required string funCodeMeaning = 11;</code>
     */
    public String getFunCodeMeaning() {
      Object ref = funCodeMeaning_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          funCodeMeaning_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string funCodeMeaning = 11;</code>
     */
    public com.google.protobuf.ByteString
        getFunCodeMeaningBytes() {
      Object ref = funCodeMeaning_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        funCodeMeaning_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DELAY_FIELD_NUMBER = 12;
    private int delay_;
    /**
     * <code>required int32 delay = 12;</code>
     */
    public boolean hasDelay() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>required int32 delay = 12;</code>
     */
    public int getDelay() {
      return delay_;
    }

    public static final int COLLECTORID_FIELD_NUMBER = 13;
    private int collectorId_;
    /**
     * <code>required int32 collectorId = 13;</code>
     */
    public boolean hasCollectorId() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>required int32 collectorId = 13;</code>
     */
    public int getCollectorId() {
      return collectorId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFrameProtocols()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEthDst()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrameCapLen()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEthSrc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpSrc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIpDst()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSrcPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDstPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimeStamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFunCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFunCodeMeaning()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDelay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCollectorId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, frameProtocols_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ethDst_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, frameCapLen_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ethSrc_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ipSrc_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ipDst_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, srcPort_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, dstPort_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, timeStamp_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, funCode_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, funCodeMeaning_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        output.writeInt32(12, delay_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        output.writeInt32(13, collectorId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, frameProtocols_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ethDst_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, frameCapLen_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ethSrc_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ipSrc_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ipDst_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, srcPort_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, dstPort_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, timeStamp_);
      }
      if (((bitField0_ & 0x00000200) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, funCode_);
      }
      if (((bitField0_ & 0x00000400) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, funCodeMeaning_);
      }
      if (((bitField0_ & 0x00000800) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, delay_);
      }
      if (((bitField0_ & 0x00001000) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, collectorId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FvDimensionLayer)) {
        return super.equals(obj);
      }
      FvDimensionLayer other = (FvDimensionLayer) obj;

      if (hasFrameProtocols() != other.hasFrameProtocols()) return false;
      if (hasFrameProtocols()) {
        if (!getFrameProtocols()
            .equals(other.getFrameProtocols())) return false;
      }
      if (hasEthDst() != other.hasEthDst()) return false;
      if (hasEthDst()) {
        if (!getEthDst()
            .equals(other.getEthDst())) return false;
      }
      if (hasFrameCapLen() != other.hasFrameCapLen()) return false;
      if (hasFrameCapLen()) {
        if (!getFrameCapLen()
            .equals(other.getFrameCapLen())) return false;
      }
      if (hasEthSrc() != other.hasEthSrc()) return false;
      if (hasEthSrc()) {
        if (!getEthSrc()
            .equals(other.getEthSrc())) return false;
      }
      if (hasIpSrc() != other.hasIpSrc()) return false;
      if (hasIpSrc()) {
        if (!getIpSrc()
            .equals(other.getIpSrc())) return false;
      }
      if (hasIpDst() != other.hasIpDst()) return false;
      if (hasIpDst()) {
        if (!getIpDst()
            .equals(other.getIpDst())) return false;
      }
      if (hasSrcPort() != other.hasSrcPort()) return false;
      if (hasSrcPort()) {
        if (!getSrcPort()
            .equals(other.getSrcPort())) return false;
      }
      if (hasDstPort() != other.hasDstPort()) return false;
      if (hasDstPort()) {
        if (!getDstPort()
            .equals(other.getDstPort())) return false;
      }
      if (hasTimeStamp() != other.hasTimeStamp()) return false;
      if (hasTimeStamp()) {
        if (!getTimeStamp()
            .equals(other.getTimeStamp())) return false;
      }
      if (hasFunCode() != other.hasFunCode()) return false;
      if (hasFunCode()) {
        if (!getFunCode()
            .equals(other.getFunCode())) return false;
      }
      if (hasFunCodeMeaning() != other.hasFunCodeMeaning()) return false;
      if (hasFunCodeMeaning()) {
        if (!getFunCodeMeaning()
            .equals(other.getFunCodeMeaning())) return false;
      }
      if (hasDelay() != other.hasDelay()) return false;
      if (hasDelay()) {
        if (getDelay()
            != other.getDelay()) return false;
      }
      if (hasCollectorId() != other.hasCollectorId()) return false;
      if (hasCollectorId()) {
        if (getCollectorId()
            != other.getCollectorId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrameProtocols()) {
        hash = (37 * hash) + FRAME_PROTOCOLS_FIELD_NUMBER;
        hash = (53 * hash) + getFrameProtocols().hashCode();
      }
      if (hasEthDst()) {
        hash = (37 * hash) + ETH_DST_FIELD_NUMBER;
        hash = (53 * hash) + getEthDst().hashCode();
      }
      if (hasFrameCapLen()) {
        hash = (37 * hash) + FRAME_CAP_LEN_FIELD_NUMBER;
        hash = (53 * hash) + getFrameCapLen().hashCode();
      }
      if (hasEthSrc()) {
        hash = (37 * hash) + ETH_SRC_FIELD_NUMBER;
        hash = (53 * hash) + getEthSrc().hashCode();
      }
      if (hasIpSrc()) {
        hash = (37 * hash) + IP_SRC_FIELD_NUMBER;
        hash = (53 * hash) + getIpSrc().hashCode();
      }
      if (hasIpDst()) {
        hash = (37 * hash) + IP_DST_FIELD_NUMBER;
        hash = (53 * hash) + getIpDst().hashCode();
      }
      if (hasSrcPort()) {
        hash = (37 * hash) + SRC_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getSrcPort().hashCode();
      }
      if (hasDstPort()) {
        hash = (37 * hash) + DST_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getDstPort().hashCode();
      }
      if (hasTimeStamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimeStamp().hashCode();
      }
      if (hasFunCode()) {
        hash = (37 * hash) + FUNCODE_FIELD_NUMBER;
        hash = (53 * hash) + getFunCode().hashCode();
      }
      if (hasFunCodeMeaning()) {
        hash = (37 * hash) + FUNCODEMEANING_FIELD_NUMBER;
        hash = (53 * hash) + getFunCodeMeaning().hashCode();
      }
      if (hasDelay()) {
        hash = (37 * hash) + DELAY_FIELD_NUMBER;
        hash = (53 * hash) + getDelay();
      }
      if (hasCollectorId()) {
        hash = (37 * hash) + COLLECTORID_FIELD_NUMBER;
        hash = (53 * hash) + getCollectorId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FvDimensionLayer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FvDimensionLayer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FvDimensionLayer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FvDimensionLayer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FvDimensionLayer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FvDimensionLayer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FvDimensionLayer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FvDimensionLayer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FvDimensionLayer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FvDimensionLayer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FvDimensionLayer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FvDimensionLayer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FvDimensionLayer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *定义结构数据
     * </pre>
     *
     * Protobuf type {@code com.zjucsc.FvDimensionLayer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.zjucsc.FvDimensionLayer)
        FvDimensionLayerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_com_zjucsc_FvDimensionLayer_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_com_zjucsc_FvDimensionLayer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FvDimensionLayer.class, FvDimensionLayer.Builder.class);
      }

      // Construct using FvDimensionLayer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        frameProtocols_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        ethDst_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        frameCapLen_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        ethSrc_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        ipSrc_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        ipDst_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        srcPort_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        dstPort_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        timeStamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        funCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        funCodeMeaning_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        delay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        collectorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_com_zjucsc_FvDimensionLayer_descriptor;
      }

      @Override
      public FvDimensionLayer getDefaultInstanceForType() {
        return FvDimensionLayer.getDefaultInstance();
      }

      @Override
      public FvDimensionLayer build() {
        FvDimensionLayer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FvDimensionLayer buildPartial() {
        FvDimensionLayer result = new FvDimensionLayer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.frameProtocols_ = frameProtocols_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ethDst_ = ethDst_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.frameCapLen_ = frameCapLen_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ethSrc_ = ethSrc_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ipSrc_ = ipSrc_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.ipDst_ = ipDst_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.srcPort_ = srcPort_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.dstPort_ = dstPort_;
        if (((from_bitField0_ & 0x00000100) != 0)) {
          to_bitField0_ |= 0x00000100;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000200) != 0)) {
          to_bitField0_ |= 0x00000200;
        }
        result.funCode_ = funCode_;
        if (((from_bitField0_ & 0x00000400) != 0)) {
          to_bitField0_ |= 0x00000400;
        }
        result.funCodeMeaning_ = funCodeMeaning_;
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.delay_ = delay_;
          to_bitField0_ |= 0x00000800;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.collectorId_ = collectorId_;
          to_bitField0_ |= 0x00001000;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FvDimensionLayer) {
          return mergeFrom((FvDimensionLayer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FvDimensionLayer other) {
        if (other == FvDimensionLayer.getDefaultInstance()) return this;
        if (other.hasFrameProtocols()) {
          bitField0_ |= 0x00000001;
          frameProtocols_ = other.frameProtocols_;
          onChanged();
        }
        if (other.hasEthDst()) {
          bitField0_ |= 0x00000002;
          ethDst_ = other.ethDst_;
          onChanged();
        }
        if (other.hasFrameCapLen()) {
          bitField0_ |= 0x00000004;
          frameCapLen_ = other.frameCapLen_;
          onChanged();
        }
        if (other.hasEthSrc()) {
          bitField0_ |= 0x00000008;
          ethSrc_ = other.ethSrc_;
          onChanged();
        }
        if (other.hasIpSrc()) {
          bitField0_ |= 0x00000010;
          ipSrc_ = other.ipSrc_;
          onChanged();
        }
        if (other.hasIpDst()) {
          bitField0_ |= 0x00000020;
          ipDst_ = other.ipDst_;
          onChanged();
        }
        if (other.hasSrcPort()) {
          bitField0_ |= 0x00000040;
          srcPort_ = other.srcPort_;
          onChanged();
        }
        if (other.hasDstPort()) {
          bitField0_ |= 0x00000080;
          dstPort_ = other.dstPort_;
          onChanged();
        }
        if (other.hasTimeStamp()) {
          bitField0_ |= 0x00000100;
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (other.hasFunCode()) {
          bitField0_ |= 0x00000200;
          funCode_ = other.funCode_;
          onChanged();
        }
        if (other.hasFunCodeMeaning()) {
          bitField0_ |= 0x00000400;
          funCodeMeaning_ = other.funCodeMeaning_;
          onChanged();
        }
        if (other.hasDelay()) {
          setDelay(other.getDelay());
        }
        if (other.hasCollectorId()) {
          setCollectorId(other.getCollectorId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasFrameProtocols()) {
          return false;
        }
        if (!hasEthDst()) {
          return false;
        }
        if (!hasFrameCapLen()) {
          return false;
        }
        if (!hasEthSrc()) {
          return false;
        }
        if (!hasIpSrc()) {
          return false;
        }
        if (!hasIpDst()) {
          return false;
        }
        if (!hasSrcPort()) {
          return false;
        }
        if (!hasDstPort()) {
          return false;
        }
        if (!hasTimeStamp()) {
          return false;
        }
        if (!hasFunCode()) {
          return false;
        }
        if (!hasFunCodeMeaning()) {
          return false;
        }
        if (!hasDelay()) {
          return false;
        }
        if (!hasCollectorId()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FvDimensionLayer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FvDimensionLayer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object frameProtocols_ = "";
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string frame_protocols = 1;</code>
       */
      public boolean hasFrameProtocols() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string frame_protocols = 1;</code>
       */
      public String getFrameProtocols() {
        Object ref = frameProtocols_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            frameProtocols_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string frame_protocols = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFrameProtocolsBytes() {
        Object ref = frameProtocols_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          frameProtocols_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string frame_protocols = 1;</code>
       */
      public Builder setFrameProtocols(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        frameProtocols_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string frame_protocols = 1;</code>
       */
      public Builder clearFrameProtocols() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frameProtocols_ = getDefaultInstance().getFrameProtocols();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必选字段 第1个属性
       * </pre>
       *
       * <code>required string frame_protocols = 1;</code>
       */
      public Builder setFrameProtocolsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        frameProtocols_ = value;
        onChanged();
        return this;
      }

      private Object ethDst_ = "";
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string eth_dst = 2;</code>
       */
      public boolean hasEthDst() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string eth_dst = 2;</code>
       */
      public String getEthDst() {
        Object ref = ethDst_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ethDst_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string eth_dst = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEthDstBytes() {
        Object ref = ethDst_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ethDst_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string eth_dst = 2;</code>
       */
      public Builder setEthDst(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ethDst_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string eth_dst = 2;</code>
       */
      public Builder clearEthDst() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ethDst_ = getDefaultInstance().getEthDst();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *必选字段 第2个属性
       * </pre>
       *
       * <code>required string eth_dst = 2;</code>
       */
      public Builder setEthDstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ethDst_ = value;
        onChanged();
        return this;
      }

      private Object frameCapLen_ = "";
      /**
       * <pre>
       *可选字段 第3个属性
       * </pre>
       *
       * <code>required string frame_cap_len = 3;</code>
       */
      public boolean hasFrameCapLen() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *可选字段 第3个属性
       * </pre>
       *
       * <code>required string frame_cap_len = 3;</code>
       */
      public String getFrameCapLen() {
        Object ref = frameCapLen_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            frameCapLen_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *可选字段 第3个属性
       * </pre>
       *
       * <code>required string frame_cap_len = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFrameCapLenBytes() {
        Object ref = frameCapLen_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          frameCapLen_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *可选字段 第3个属性
       * </pre>
       *
       * <code>required string frame_cap_len = 3;</code>
       */
      public Builder setFrameCapLen(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        frameCapLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *可选字段 第3个属性
       * </pre>
       *
       * <code>required string frame_cap_len = 3;</code>
       */
      public Builder clearFrameCapLen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        frameCapLen_ = getDefaultInstance().getFrameCapLen();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *可选字段 第3个属性
       * </pre>
       *
       * <code>required string frame_cap_len = 3;</code>
       */
      public Builder setFrameCapLenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        frameCapLen_ = value;
        onChanged();
        return this;
      }

      private Object ethSrc_ = "";
      /**
       * <code>required string eth_src = 4;</code>
       */
      public boolean hasEthSrc() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string eth_src = 4;</code>
       */
      public String getEthSrc() {
        Object ref = ethSrc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ethSrc_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string eth_src = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEthSrcBytes() {
        Object ref = ethSrc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ethSrc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string eth_src = 4;</code>
       */
      public Builder setEthSrc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ethSrc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string eth_src = 4;</code>
       */
      public Builder clearEthSrc() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ethSrc_ = getDefaultInstance().getEthSrc();
        onChanged();
        return this;
      }
      /**
       * <code>required string eth_src = 4;</code>
       */
      public Builder setEthSrcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        ethSrc_ = value;
        onChanged();
        return this;
      }

      private Object ipSrc_ = "";
      /**
       * <code>required string ip_src = 5;</code>
       */
      public boolean hasIpSrc() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string ip_src = 5;</code>
       */
      public String getIpSrc() {
        Object ref = ipSrc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipSrc_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ip_src = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIpSrcBytes() {
        Object ref = ipSrc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ipSrc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip_src = 5;</code>
       */
      public Builder setIpSrc(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ipSrc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_src = 5;</code>
       */
      public Builder clearIpSrc() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ipSrc_ = getDefaultInstance().getIpSrc();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_src = 5;</code>
       */
      public Builder setIpSrcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ipSrc_ = value;
        onChanged();
        return this;
      }

      private Object ipDst_ = "";
      /**
       * <code>required string ip_dst = 6;</code>
       */
      public boolean hasIpDst() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string ip_dst = 6;</code>
       */
      public String getIpDst() {
        Object ref = ipDst_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipDst_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ip_dst = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIpDstBytes() {
        Object ref = ipDst_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ipDst_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip_dst = 6;</code>
       */
      public Builder setIpDst(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ipDst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_dst = 6;</code>
       */
      public Builder clearIpDst() {
        bitField0_ = (bitField0_ & ~0x00000020);
        ipDst_ = getDefaultInstance().getIpDst();
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_dst = 6;</code>
       */
      public Builder setIpDstBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        ipDst_ = value;
        onChanged();
        return this;
      }

      private Object srcPort_ = "";
      /**
       * <code>required string src_port = 7;</code>
       */
      public boolean hasSrcPort() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required string src_port = 7;</code>
       */
      public String getSrcPort() {
        Object ref = srcPort_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            srcPort_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string src_port = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSrcPortBytes() {
        Object ref = srcPort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          srcPort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string src_port = 7;</code>
       */
      public Builder setSrcPort(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        srcPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string src_port = 7;</code>
       */
      public Builder clearSrcPort() {
        bitField0_ = (bitField0_ & ~0x00000040);
        srcPort_ = getDefaultInstance().getSrcPort();
        onChanged();
        return this;
      }
      /**
       * <code>required string src_port = 7;</code>
       */
      public Builder setSrcPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        srcPort_ = value;
        onChanged();
        return this;
      }

      private Object dstPort_ = "";
      /**
       * <code>required string dst_port = 8;</code>
       */
      public boolean hasDstPort() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>required string dst_port = 8;</code>
       */
      public String getDstPort() {
        Object ref = dstPort_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dstPort_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string dst_port = 8;</code>
       */
      public com.google.protobuf.ByteString
          getDstPortBytes() {
        Object ref = dstPort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dstPort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dst_port = 8;</code>
       */
      public Builder setDstPort(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        dstPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dst_port = 8;</code>
       */
      public Builder clearDstPort() {
        bitField0_ = (bitField0_ & ~0x00000080);
        dstPort_ = getDefaultInstance().getDstPort();
        onChanged();
        return this;
      }
      /**
       * <code>required string dst_port = 8;</code>
       */
      public Builder setDstPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        dstPort_ = value;
        onChanged();
        return this;
      }

      private Object timeStamp_ = "";
      /**
       * <code>required string timeStamp = 9;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>required string timeStamp = 9;</code>
       */
      public String getTimeStamp() {
        Object ref = timeStamp_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timeStamp_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string timeStamp = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timeStamp = 9;</code>
       */
      public Builder setTimeStamp(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timeStamp = 9;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000100);
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timeStamp = 9;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private Object funCode_ = "";
      /**
       * <code>required string funCode = 10;</code>
       */
      public boolean hasFunCode() {
        return ((bitField0_ & 0x00000200) != 0);
      }
      /**
       * <code>required string funCode = 10;</code>
       */
      public String getFunCode() {
        Object ref = funCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            funCode_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string funCode = 10;</code>
       */
      public com.google.protobuf.ByteString
          getFunCodeBytes() {
        Object ref = funCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          funCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string funCode = 10;</code>
       */
      public Builder setFunCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        funCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string funCode = 10;</code>
       */
      public Builder clearFunCode() {
        bitField0_ = (bitField0_ & ~0x00000200);
        funCode_ = getDefaultInstance().getFunCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string funCode = 10;</code>
       */
      public Builder setFunCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        funCode_ = value;
        onChanged();
        return this;
      }

      private Object funCodeMeaning_ = "";
      /**
       * <code>required string funCodeMeaning = 11;</code>
       */
      public boolean hasFunCodeMeaning() {
        return ((bitField0_ & 0x00000400) != 0);
      }
      /**
       * <code>required string funCodeMeaning = 11;</code>
       */
      public String getFunCodeMeaning() {
        Object ref = funCodeMeaning_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            funCodeMeaning_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string funCodeMeaning = 11;</code>
       */
      public com.google.protobuf.ByteString
          getFunCodeMeaningBytes() {
        Object ref = funCodeMeaning_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          funCodeMeaning_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string funCodeMeaning = 11;</code>
       */
      public Builder setFunCodeMeaning(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        funCodeMeaning_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string funCodeMeaning = 11;</code>
       */
      public Builder clearFunCodeMeaning() {
        bitField0_ = (bitField0_ & ~0x00000400);
        funCodeMeaning_ = getDefaultInstance().getFunCodeMeaning();
        onChanged();
        return this;
      }
      /**
       * <code>required string funCodeMeaning = 11;</code>
       */
      public Builder setFunCodeMeaningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        funCodeMeaning_ = value;
        onChanged();
        return this;
      }

      private int delay_ ;
      /**
       * <code>required int32 delay = 12;</code>
       */
      public boolean hasDelay() {
        return ((bitField0_ & 0x00000800) != 0);
      }
      /**
       * <code>required int32 delay = 12;</code>
       */
      public int getDelay() {
        return delay_;
      }
      /**
       * <code>required int32 delay = 12;</code>
       */
      public Builder setDelay(int value) {
        bitField0_ |= 0x00000800;
        delay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 delay = 12;</code>
       */
      public Builder clearDelay() {
        bitField0_ = (bitField0_ & ~0x00000800);
        delay_ = 0;
        onChanged();
        return this;
      }

      private int collectorId_ ;
      /**
       * <code>required int32 collectorId = 13;</code>
       */
      public boolean hasCollectorId() {
        return ((bitField0_ & 0x00001000) != 0);
      }
      /**
       * <code>required int32 collectorId = 13;</code>
       */
      public int getCollectorId() {
        return collectorId_;
      }
      /**
       * <code>required int32 collectorId = 13;</code>
       */
      public Builder setCollectorId(int value) {
        bitField0_ |= 0x00001000;
        collectorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 collectorId = 13;</code>
       */
      public Builder clearCollectorId() {
        bitField0_ = (bitField0_ & ~0x00001000);
        collectorId_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.zjucsc.FvDimensionLayer)
    }

    // @@protoc_insertion_point(class_scope:com.zjucsc.FvDimensionLayer)
    private static final FvDimensionLayer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FvDimensionLayer();
    }

    public static FvDimensionLayer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<FvDimensionLayer>
        PARSER = new com.google.protobuf.AbstractParser<FvDimensionLayer>() {
      @Override
      public FvDimensionLayer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FvDimensionLayer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FvDimensionLayer> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FvDimensionLayer> getParserForType() {
      return PARSER;
    }

    @Override
    public FvDimensionLayer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zjucsc_FvDimensionLayer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_zjucsc_FvDimensionLayer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021FvDimension.proto\022\ncom.zjucsc\"\210\002\n\020FvDi" +
      "mensionLayer\022\027\n\017frame_protocols\030\001 \002(\t\022\017\n" +
      "\007eth_dst\030\002 \002(\t\022\025\n\rframe_cap_len\030\003 \002(\t\022\017\n" +
      "\007eth_src\030\004 \002(\t\022\016\n\006ip_src\030\005 \002(\t\022\016\n\006ip_dst" +
      "\030\006 \002(\t\022\020\n\010src_port\030\007 \002(\t\022\020\n\010dst_port\030\010 \002" +
      "(\t\022\021\n\ttimeStamp\030\t \002(\t\022\017\n\007funCode\030\n \002(\t\022\026" +
      "\n\016funCodeMeaning\030\013 \002(\t\022\r\n\005delay\030\014 \002(\005\022\023\n" +
      "\013collectorId\030\r \002(\005"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_zjucsc_FvDimensionLayer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_zjucsc_FvDimensionLayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_zjucsc_FvDimensionLayer_descriptor,
        new String[] { "FrameProtocols", "EthDst", "FrameCapLen", "EthSrc", "IpSrc", "IpDst", "SrcPort", "DstPort", "TimeStamp", "FunCode", "FunCodeMeaning", "Delay", "CollectorId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
