myconfig :
  host[0] : http://localhost:8080/
  host[1] : http://localhost:8083/
  showLog : true

spring:
  application:
    name: zuul-center
server:
  port: 7575
  address: localhost

zuul:
  routes:
    api-a-path:
      path : /api-a-url/**
    api-a-url:
      url : http://localhost:8080/error   #default url